# Generated by Django 3.1.4 on 2020-12-19 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Toping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=75, unique=True)),
                ('title', models.CharField(db_index=True, max_length=25, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Топинг',
                'verbose_name_plural': 'Топинги',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=75, unique=True)),
                ('title', models.CharField(db_index=True, max_length=25, verbose_name='Название')),
                ('content', models.TextField(blank=True, verbose_name='Описание')),
                ('cook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('topings', models.ManyToManyField(blank=True, related_name='Топинги', to='mysite.Toping')),
            ],
            options={
                'verbose_name': 'Пицца',
                'verbose_name_plural': 'Пиццы',
                'ordering': ['title'],
            },
        ),
    ]
